name: Node PR Lint, Build and Test

on:
  # Trigger when manually run
  workflow_dispatch:

  # Trigger on pushes to `main` or `rel/*`
  push:
    branches:
      - main
      - rel/*

  # Trigger on pull requests to `main` or `rel/*`
  pull_request:
    branches:
      - main
      - rel/*

jobs:
  Build:
    steps:

      - if: runner.os == 'Windows'
        name: Install Ballerina (Windows)
        run: |
          curl -o ballerina.msi https://dist.ballerina.io/downloads/2201.6.0/ballerina-2201.6.0-swan-lake-windows-x64.msi
          msiexec /i ballerina.msi /quiet /qr /L*V "C:\Temp\msilog.log"
          del ballerina.msi
          echo "##vso[task.setvariable variable=PATH]C:\Program Files\Ballerina\bin;$(PATH)"

      - if: runner.os == 'Linux'
        name: Install Ballerina (Linux)
        run: |
          curl -o ballerina.deb 'https://dist.ballerina.io/downloads/2201.6.0/ballerina-2201.6.0-swan-lake-linux-x64.deb'
          sudo dpkg -i ballerina.deb
          rm -f ballerina.deb

      - if: runner.os == 'macOS'
        name: Install Ballerina (macOS)
        run: |
          curl -o ballerina.pkg 'https://dist.ballerina.io/downloads/2201.6.0/ballerina-2201.6.0-swan-lake-macos-x64.pkg'
          sudo installer -pkg ballerina.pkg -target /
          rm -f ballerina.pkg
          echo '##vso[task.prependpath]/Library/Ballerina/bin'

      # Use template from https://github.com/microsoft/vscode-azuretools/tree/main/.github/workflows
      uses: microsoft/vscode-azuretools/.github/workflows/jobs.yml@main
